#!/bin/bash

cpp="gcc -E"

$cpp -D "__attribute__(ARGS)=" \
    -D "__align__(ARGS)=" \
    -D "aligned(ARGS)=" \
    -D "_Nonnull=" \
    -D "_Nullable=" \
    -D "__extension__=" \
    -D "__asm__(ARGS)=" \
    $1 $2 > $2.c4
